### ISSUE TITLE
Datamapper 1.2

### ISSUE THREAD

**Issue by pcdoc80** [snusnu/dm-accepts_nested_attributes#10]
Hi,

I have a question: How can I install this gem with datamapper 1.2? When in install the gem with "gem instal ..." I see that the master branch depends on datamapper < 1.2.

Thanks in advance,
pcdoc80

**Comment by nacengineer** [comment]
why was this closed? Its still an issue as far as I can tell? Am I missing something. Was this absorbed into dm-core?

**Comment by nacengineer** [comment]
Perhaps because a fork fixes it? not sure. https://github.com/waelchatila/dm-accepts_nested_attributes

**Comment by mltsy** [comment]
I have the same question.  It would be nice to reopen the issue, since it doesn't seem to be resolved... ?  Perhaps it's just not compatible yet?

**Comment by mltsy** [comment]
@snusnu told me on #datamapper that he just hasn't gotten around to updating it yet, but the refactor branch should be compatible with the DM master source.  I didn't want to upgrade all the way to the latest HEAD, so I tried the release-1.2 branch just now, which he said is stable as well, and it seems to be working fine!  (in the gemfile, just add a `, :branch => 'release-1.2'` to the end of the line)
