### ISSUE TITLE
Push the 1.1.0 gem on rubygems

### ISSUE THREAD

**Issue by shingara** [snusnu/dm-accepts_nested_attributes#14]
The branch https://github.com/snusnu/dm-accepts_nested_attributes/tree/release-1.2 has a version 1.1.0 but rubygems doesn't know it.

Can you push this version on rubygems ?

**Comment by pschuegr** [comment]
Yes please!

**Comment by snusnu** [comment]
I bumped the version to 1.2.0 in the release-1.2 branch and will release it within the next few days. Thx for the patience, sorry for any inconveniences!
