### ISSUE TITLE
association update is not wrapped inside transaction

### ISSUE THREAD

**Issue by trungpham** [snusnu/dm-accepts_nested_attributes#4]
but creating new association object does.

post.comments_attributes = [{:id => 1, :body => 'blah'}]
post.title = 'new title'
post.save #update to comment is not in the transaction block

post.comments_attributes = [{:body => 'blah'}]
post.title = 'new title'
post.save #both update to post and insert to comment are in the same transaction block.

thank you.

**Comment by snusnu** [comment]
I started refactoring the specs a bit mainly to become familiar with all this stuff again. I will try to work through these issues in the next days, but I'd greatly appreciate any help from your side! :) That doesn't necessarily mean that you'd need to send patches to correct the behavior, but failing specs would certainly be appreciated! (of course, patches that fix the errorneous behavior too :)

**Comment by gix** [comment]
Transactional behavior has been removed (see c17343ef3f93b945980bbcc0d41480433b3cf8fb).
