### ISSUE TITLE
Destroying child models for has n

### ISSUE THREAD

**Issue by activestylus** [snusnu/dm-accepts_nested_attributes#5]
I cant seem to delete children

The Model:

```
class Site
  has n, :pages
  accepts_nested_attributes_for :pages
```

The View:

```
= f.fields_for :pages do |p|
  ...
  = link_to 'Remove', '#'
  p.hidden_field('_destroy', :value => 0)
```

If I omit that last line I can add child models, but whenever I have it in there I get:

**The attribute '_destroy' is not accessible in Page**

Am I using the wrong attribute for deletion? I had assumed it would be identical to activerecord

**Comment by abevoelker** [comment]
I had the same confusion. The correct attribute is `:_delete` (had to look through the source code to find it).

**Comment by g3d** [comment]
I get `The attribute '_delete' is not accessible in Tagging`

for code:

```
- f.fields_for :taggings do |address_form|
  = address_form.label :post_id
  = address_form.text_field :post_id
  = address_form.label :tag_id
  = address_form.text_field :tag_id
  - unless address_form.object.new_record?
    = address_form.check_box :_delete
    = address_form.label :_delete, :caption => 'Remove'
  = submit_tag "Save"
```

My models is:

```
class Post
  include DataMapper::Resource

  belongs_to :account
  has n, :taggings
  has n, :tags, :through => :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true
  ...

end

class Tag
  include DataMapper::Resource

  has n, :taggings
  has n, :posts, :through => :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true
  ...

end

class Tagging
  include DataMapper::Resource

  # property <name>, <type>
  property :id, Serial
  property :post_id, Integer
  property :tag_id, Integer

  belongs_to :tag,  :key => true
  belongs_to :post, :key => true

  alias_method :new_record?, :new?

end
```

If i use `_destroy` i got the same error

**Comment by ryudice** [comment]
I'm having the same issue, using datamapper has to be the worst decision I have ever made on a project, the ecosystem is shit, going back to AR.

**Comment by shingara** [comment]
@g3d you need fix the value of your checkbox and it's works :

```
= address_form.check_box :_delete, :value => false
```

**Comment by snusnu** [comment]
Also, see af5c14345b9ee872e7fe2bcf84cd5632a5621ac9 for an app wide way to configure this. I will release a new version soon, now that i've got travis working. Thx for the patience, sorry for any inconveniences.
